apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: acme-order
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: acme-fitness-store
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    subPath: apps/acme-order
    git:
      url: https://github.com/odedia/acme-fitness-store
      ref:
        branch: main
