#@ load("@ytt:data", "data")
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: acme-fitness-gateway-httpproxy
spec:
  virtualhost:
    fqdn: #@ "acme-fitness.{}".format(data.values.ingress.fqdn)
    tls:
      secretName: #@ "tanzu-system-ingress/{}".format(data.values.ingress.contour_tls_secret)
  routes:
    - conditions:
      - prefix: /
      services:
      - name: acme-fitness-gateway
        port: 80